# Generated by Django 3.2.4 on 2021-12-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='icon_select',
            field=models.CharField(choices=[('lni-briefcase', 'marketing'), ('lni-pencil', 'caneta'), ('lni-tab', 'app_dev'), ('lni-cog', 'web_dev'), ('lni-layers', 'ui_ux_design'), ('lni-stats-up', 'grafico')], max_length=20),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
