# Generated by Django 4.0.4 on 2022-05-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211213_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='icon_select',
            field=models.CharField(choices=[('lni-stats-up', 'grafico'), ('lni-briefcase', 'marketing'), ('lni-layers', 'ui_ux_design'), ('lni-cog', 'web_dev'), ('lni-tab', 'app_dev'), ('lni-pencil', 'caneta')], max_length=20),
        ),
    ]
