# Generated by Django 4.0.4 on 2022-05-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_team_alter_about_icon_select'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('about', models.TextField(max_length=150)),
                ('icon_select', models.CharField(choices=[('lni-tab', 'responsivo'), ('lni-database', 'dados'), ('lni-rocket', 'foguete'), ('lni-leaf', 'folha'), ('lni-pencil', 'caneta'), ('lni-layout', 'quadro')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='icon_select',
            field=models.CharField(choices=[('lni-briefcase', 'marketing'), ('lni-tab', 'app_dev'), ('lni-layers', 'ui_ux_design'), ('lni-cog', 'web_dev'), ('lni-pencil', 'caneta'), ('lni-stats-up', 'grafico')], max_length=20),
        ),
    ]
