# Generated by Django 4.0.4 on 2022-05-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_feature_alter_about_icon_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='icon_select',
            field=models.CharField(choices=[('lni-tab', 'app_dev'), ('lni-cog', 'web_dev'), ('lni-briefcase', 'marketing'), ('lni-stats-up', 'grafico'), ('lni-pencil', 'caneta'), ('lni-layers', 'ui_ux_design')], max_length=20),
        ),
        migrations.AlterField(
            model_name='feature',
            name='icon_select',
            field=models.CharField(choices=[('lni-database', 'dados'), ('lni-tab', 'responsivo'), ('lni-rocket', 'foguete'), ('lni-layout', 'quadro'), ('lni-pencil', 'caneta'), ('lni-leaf', 'folha')], max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(height_field=250, upload_to='img/', width_field=250),
        ),
    ]
