# Generated by Django 4.0.4 on 2022-05-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_about_icon_select_alter_feature_icon_select_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='facebook',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='linkedIn',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='tumbrl',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='twiiter',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='icon_select',
            field=models.CharField(choices=[('lni-stats-up', 'grafico'), ('lni-pencil', 'caneta'), ('lni-layers', 'ui_ux_design'), ('lni-cog', 'web_dev'), ('lni-tab', 'app_dev'), ('lni-briefcase', 'marketing')], max_length=20),
        ),
        migrations.AlterField(
            model_name='feature',
            name='icon_select',
            field=models.CharField(choices=[('lni-tab', 'responsivo'), ('lni-rocket', 'foguete'), ('lni-database', 'dados'), ('lni-layout', 'quadro'), ('lni-pencil', 'caneta'), ('lni-leaf', 'folha')], max_length=20),
        ),
    ]
